# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "xterm-256color"

unbind C-b
set-option -g prefix M-i

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind r source-file ~/.config/tmux/tmux.conf

set-option -g mouse on

bind -n M-N new-window -c '#{pane_current_path}'
bind -n M-C kill-pane

bind -n M-H previous-window
bind -n M-L next-window

# panes
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind -r k select-pane -U
bind -r j select-pane -D 
bind -r h select-pane -L
bind -r l select-pane -R

#pane border
set -g pane-active-border-style fg=royalblue
set -g pane-border-style fg=#000000


# Status bar
set -g status-style 'bg=default fg=#caddeb'

set -g status-justify centre
# set -g status-left 'tmux'
set -g status-left '#[bg=#{?client_prefix,royalblue,default}] tmux '
set -g status-right ' #{session_name} '

set -g window-status-format '#[bold fg=#7b8496]   #W   '
set -g window-status-current-format '#[bold fg=white]   #W   '

# Optional: dim the inactive ones a bit
# set -g window-status-style 'fg=#888888'
# set -g window-status-current-style 'fg=blue bold'
